### ISSUE TITLE
不要关键词直接对话怎么配置？

### ISSUE THREAD

**Issue by samcaicn** [saurlax/koishi-plugin-maxkb#1]
嗯嗯 大神

**Comment by saurlax** [comment]
因为 koishi 同时支持群聊模式和私聊模式，如果在群聊模式下可以直接触发会导致过度刷屏/回复不相干的内容。请问您是想在私聊模式下直接回复消息吗？这个一开始确实没考虑到，后续会实现

**Comment by samcaicn** [comment]
谢谢！ 能否写个正则临时先用着！
命中标点符号的就可以！

看是否方便加我微信526218543
各位有想聊的，我也建了个群讨论【拱手】

**Comment by saurlax** [comment]
私聊触发功能已添加，可以在插件配置中根据提示进入依赖管理界面升级插件

![image](https://github.com/user-attachments/assets/beed6c56-00f5-4d44-a523-755c5cd9dcf7)

**Comment by saurlax** [comment]
> 谢谢！ 能否写个正则临时先用着！ 命中标点符号的就可以！

可以的，开启关键词触发模式，然后将关键词留空，这样将会回复所有的消息，无论群聊还是私聊模式

**Comment by samcaicn** [comment]
无论群聊还是私聊模式""



不觉得又些不妥吗？

**Comment by saurlax** [comment]
> 无论群聊还是私聊模式""
> 
> 不觉得又些不妥吗？

这个是用户自行设置决定的，既然将关键词留空了，自然代表匹配所有的消息

- 如果想要在私聊的情况下直接的对话，目前默认自动开启私聊触发模式，无需设置就可以在私聊模式下对话
- 群聊中为了避免刷屏，只有在@机器人的情况下才会回复，@机器人触发也是默认开启的
- 如果希望在群聊中回复所有人的消息，打开关键词模式，然后留空关键词，这样就会回复所有的消息

**Comment by samcaicn** [comment]
这逻辑我只能说太聪明了

小建议：
私聊按你的逻辑来。

群聊@ 加上你的逻辑组合
